### PR TITLE
Add getRoomMessages function

### PR DESCRIPTION
**Pull request by morrislaptop**
### What?

Add getRoomMessages function

### Why?

Because it's possible with REST API but wasn't in the library

----

Similar to #19 - I get a "Missing token subject" without supplying a user id, but I can enter any random user id and it works. This would be a problem on the API side I guess?

### CODE REVIEW

**Comment by hamchapman** [comment]
I've got a pull request for the server prepared (just need a review and a deploy) that will remove the subject requirement in the token again. So same as before, once that's merged, I'll get this merged and remove the need for providing the user ID when generating the token.

Thanks again! Loving these PRs rolling in at a rapid rate!

**Comment by morrislaptop** [comment]
* bump

**Comment by morrislaptop** [comment]
@hamchapman ?

**Comment by hamchapman** [comment]
I’m out of the office this week but I’ll revisit this on Monday 👍

**Comment by morrislaptop** [comment]
@hamchapman Thanks! I also applied for a job at Pusher, can you chase them :p

**Pull request merged**
