### PR TITLE
Add method to  get user rooms

### PR DESCRIPTION
**Pull request by shalvah**

### CODE REVIEW

**Review by callum-oakley — APPROVED** [review]
Looks good to me, thanks for this!

**Comment by callum-oakley** [comment]
That being said, might be nice to have this be two methods

`getJoinedRooms` and `getJoinableRooms`, (and call this one behind the scenes). (~WDYT @hamchapman?~ forgot you were on holiday)

**Comment by shalvah** [comment]
That makes sense @hot-leaf-jiuice. It's not a blocker to the current PR, though. 🙂

**Comment by callum-oakley** [comment]
@shalvah absolutely :slightly_smiling_face: happy to merge this and add those convenience methods at a later date

**Comment by callum-oakley** [comment]
released as 0.3.0

**Pull request merged**
